# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7vxlw-daVXeS7YWmtHc4VF1ucNZrKLK
"""



# =========================================
# 1️⃣ IMPORT & LOAD DATA
# =========================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from textblob import TextBlob
import warnings
warnings.filterwarnings("ignore")

# Load dataset
df = pd.read_csv('/content/amazon_sales_2025_INR.csv')

print("✅ Dataset Loaded Successfully!")
print(f"Shape: {df.shape}")
display(df.head())

# Check column names
print("\nColumns:")
print(df.columns.tolist())





# =========================================
# 2️⃣ BASIC ANALYSIS
# =========================================

print("\n🔹 BASIC ANALYSIS:")

# Total sales, average order value, total quantity
total_sales = df['Total_Sales_INR'].sum()
avg_order_value = df['Total_Sales_INR'].mean()
total_quantity = df['Quantity'].sum()

print(f"Total Sales (INR): {total_sales:,.2f}")
print(f"Average Order Value (INR): {avg_order_value:,.2f}")
print(f"Total Quantity Sold: {total_quantity:,}")

# Category-wise sales
category_sales = df.groupby('Product_Category')['Total_Sales_INR'].sum().sort_values(ascending=False)
print("\nCategory-wise Sales:")
display(category_sales)

# State-wise sales
state_sales = df.groupby('State')['Total_Sales_INR'].sum().sort_values(ascending=False)
print("\nState-wise Sales:")
display(state_sales)

# Payment method-wise sales
payment_sales = df.groupby('Payment_Method')['Total_Sales_INR'].sum().sort_values(ascending=False)
print("\nPayment Method-wise Sales:")
display(payment_sales)

# Top 10 products
top_products = df.groupby('Product_Name')['Total_Sales_INR'].sum().sort_values(ascending=False).head(10)
print("\nTop 10 Selling Products:")
display(top_products)





# =========================================
# 3️⃣ EXPLORATORY DATA ANALYSIS
# =========================================

print("\n🔹 EDA:")

# Convert date column to datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Extract month and year
df['Month'] = df['Date'].dt.month_name()
df['Year'] = df['Date'].dt.year

# Monthly sales
monthly_sales = df.groupby(['Year', 'Month'])['Total_Sales_INR'].sum().reset_index()

# Repeat customers
repeat_customers = df['Customer_ID'].value_counts()
repeat_customer_count = (repeat_customers > 1).sum()
print(f"Repeat Customers: {repeat_customer_count}")

# Delivery performance
print("\nDelivery Status Summary:")
display(df['Delivery_Status'].value_counts())

# Correlation between Review Rating & Sales
print("\nCorrelation between Review_Rating and Total_Sales_INR:")
display(df[['Review_Rating', 'Total_Sales_INR']].corr())





# =========================================
# 4️⃣ VISUALIZATIONS
# =========================================

# Bar chart – Top 10 Products
plt.figure(figsize=(10,6))
top_products.plot(kind='bar', color='steelblue')
plt.title('Top 10 Products by Sales')
plt.ylabel('Total Sales (INR)')
plt.xticks(rotation=75)
plt.tight_layout()
plt.show()

# Pie chart – Payment Method Share
plt.figure(figsize=(7,7))
payment_sales.plot(kind='pie', autopct='%1.1f%%', startangle=90, shadow=True)
plt.title('Payment Method Share')
plt.ylabel('')
plt.show()

# Line chart – Monthly Sales Trend
plt.figure(figsize=(10,6))
sns.lineplot(data=monthly_sales, x='Month', y='Total_Sales_INR', hue='Year', marker='o', color='purple')
plt.title('Monthly Sales Trend')
plt.ylabel('Total Sales (INR)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Heatmap – State vs Category
heatmap_data = df.pivot_table(values='Total_Sales_INR',
                              index='State',
                              columns='Product_Category',
                              aggfunc='sum',
                              fill_value=0)
plt.figure(figsize=(12,8))
sns.heatmap(heatmap_data, cmap='Blues')
plt.title('Heatmap: State vs Product Category Sales')
plt.tight_layout()
plt.show()





# =========================================
# 5️⃣ ADVANCED ANALYSIS
# =========================================

print("\n🔹 SENTIMENT ANALYSIS:")

# Sentiment from Review_Text
def get_sentiment(text):
    if pd.isna(text):
        return None
    return TextBlob(str(text)).sentiment.polarity

df['Sentiment_Score'] = df['Review_Text'].apply(get_sentiment)
df['Sentiment_Label'] = df['Sentiment_Score'].apply(
    lambda x: 'Positive' if x > 0 else ('Negative' if x < 0 else 'Neutral')
)

display(df['Sentiment_Label'].value_counts())

print("\n🔹 CUSTOMER SEGMENTATION:")

# Customer segmentation
customer_sales = df.groupby('Customer_ID')['Total_Sales_INR'].sum().reset_index()
threshold = customer_sales['Total_Sales_INR'].median()
customer_sales['Segment'] = np.where(customer_sales['Total_Sales_INR'] >= threshold,
                                     'High Value', 'Low Value')

display(customer_sales['Segment'].value_counts())

print("\n✅ All analysis completed successfully!")





# =========================================
# 1️⃣ DATA PREPROCESSING FOR ML
# =========================================

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

print("✅ Starting Machine Learning Model for Sales Prediction...\n")

# Select useful features
ml_df = df[['Product_Category', 'Product_Name', 'Quantity',
            'Unit_Price_INR', 'Review_Rating', 'Total_Sales_INR']].copy()

# Handle missing values
ml_df.dropna(inplace=True)

# Encode categorical features
le_cat = LabelEncoder()
le_name = LabelEncoder()

ml_df['Product_Category'] = le_cat.fit_transform(ml_df['Product_Category'])
ml_df['Product_Name'] = le_name.fit_transform(ml_df['Product_Name'])

# Feature and target split
X = ml_df[['Product_Category', 'Product_Name', 'Quantity', 'Unit_Price_INR', 'Review_Rating']]
y = ml_df['Total_Sales_INR']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training Data Shape: {X_train.shape}")
print(f"Testing Data Shape: {X_test.shape}")





# =========================================
# 2️⃣ TRAINING LINEAR REGRESSION MODEL
# =========================================

lr = LinearRegression()
lr.fit(X_train, y_train)

# Predictions
y_pred = lr.predict(X_test)

# Evaluate Model
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("🔹 MODEL PERFORMANCE:")
print(f"R² Score: {r2:.4f}")
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")





# =========================================
# 3️⃣ FEATURE IMPORTANCE VISUALIZATION
# =========================================

coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': lr.coef_
}).sort_values(by='Coefficient', ascending=False)

plt.figure(figsize=(8,5))
sns.barplot(x='Coefficient', y='Feature', data=coefficients, palette='coolwarm')
plt.title('Feature Importance (Linear Regression Coefficients)')
plt.tight_layout()
plt.show()

display(coefficients)





































